### ISSUE TITLE
[intensecoin-pools.morin.io] - add - itnspool.net

### ISSUE THREAD

**Issue by Venthos** [tmorin/cryptonote-universal-pool-list#24]
```
{
  "name": "itnspool.net",
  "front": "https://itnspool.net",
  "back": "https://itnspool.net/api",
  "location": "US"
}
```
comments: 0.5% fee pool located in TX, USA

**Comment by tmorin** [comment]
Hi,

Your pool sever is not https://github.com/fancoder/cryptonote-universal-pool but https://github.com/Snipa22/nodejs-pool.
So basically cryptonote-universal-pool-list is not compatible with your server.

I will try to implement the compatibility.

Best regards
