### ISSUE TITLE
[intensecoin-pools.morin.io] - update - itns.fastpool.io

### ISSUE THREAD

**Issue by Pixelcoins** [tmorin/cryptonote-universal-pool-list#36]
```
{
  "name": "itns.fastpool.io",
  "front": "http://itns.fastpool.io/",
  "back": "http://itns.fastpool.io",
  "location": "EU"
}
```

**Comment by tmorin** [comment]
Hi,
what is the requested change?
Presently the back URL is http://itns.fastpool.io:8119 because it's the back URL of your pool. If I switch to http://itns.fastpool.io cryptonote-universal-pool-list will not be able to get pool's stats.
Best regards
