### ISSUE TITLE
[intensecoin-pools.morin.io] - update - ints.novamines.com

### ISSUE THREAD

**Issue by novamines** [tmorin/cryptonote-universal-pool-list#68]
```
{
  "name": "ints.novamines.com",
  "front": "http://itns.novamines.com",
  "back": "http://itns.novamines.com:8117/stats",
  "location": "US"
}
```

**Comment by tmorin** [comment]
nothing to change ...

**Comment by novamines** [comment]
The URL of the website is displayed as "ints.novamines.com"
Should be "itns.novamines.com"
Just trying to make that little change, the rest is correct.

Best,
Nova Mines Support
-------- Original Message --------

**Comment by tmorin** [comment]
Hi
OK ;) the deploy is in progress.
Thanks

**Comment by novamines** [comment]
Thanks for the help!
-------- Original Message --------
