### ISSUE TITLE
Sumokoin pool list and filter for pool payout

### ISSUE THREAD

**Issue by Goodblue77** [tmorin/cryptonote-universal-pool-list#74]
Would be great to add a pool list for Sumokoin. Unfortunately sumopools.com isn't being updated for some time now and I really love the pool lists you guys create. A way better job than sumopools.com did.

If this can be created, could you guys please keep Hashvault off the SUMO list? They have around 50% of the network hashrate and sometimes even close to 60% which is bad for the network. We would want a more decentralized network for SUMO so keeping Hashvault off the list could be a first step.

Another thing I would love to see is a filter for the payout scheme of the pools (PROP, PPLNS etc.).

**Comment by tmorin** [comment]
Hi, thanks for the feedback.
I added sumokoin, but with only one pool.
About the the payout scheme of the pools I have to check in details how to get the info.
Best regards
