### ISSUE TITLE
npm run w:front and w:back not working

### ISSUE THREAD

**Issue by Goodblue77** [tmorin/cryptonote-universal-pool-list#75]
I don't want to be rude or anything but people wont update the pool lists if it's THIS complicated. Especially the non-techy people who don't understand anything about programming. I liked the previous solution much better where you had to fill in a form in order to get it listed on the pool.

Anyways, I get this error when I want to run the back OR frontend from the dev command prompt

listen EADDRINUSE 127.0.0.1:9000
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1343:14)
    at listenInCluster (net.js:1391:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1500:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptonote-universal-pool-list@1.4.0 w:front: `webpack-dev-server --open --hot --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cryptonote-universal-pool-list@1.4.0 w:front script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tmorin** [comment]
Hi,
I keep the tutorial for contributers/coders and I re-activated the issue wizard.
Best regards
