### ISSUE TITLE
sumo-pool.theskynet.xyz

### ISSUE THREAD

**Issue by ghost** [tmorin/cryptonote-universal-pool-list#87]
Is the minimum payout value pulled from API or manually set?
It says 5.000 for the pool, while it should be 0.5

-Ossii

**Comment by tmorin** [comment]
hi @Ossii , could you send me the link to the source code of your pool?
With nodejs-pool+poolui I'm struggling to get the right values about amount of coins.

Right now I have to do: https://github.com/tmorin/cryptonote-universal-pool-list/blob/59188b31b9211319aac9ede160aa67e907f128b8/src/front/utils.js#L14
Yes, 100000000 is a constant, but till now it worked for other nodejs-pool+poolui instances.

Thanks

**Comment by ghost** [comment]
Hmm isn't that a missing 0 for sumokoin at least?
from https://github.com/sumoprojects/sumokoin/blob/master/src/cryptonote_config.h
#define COIN                                            ((uint64_t)1000000000) // pow(10, 9)

I might be wrong, but I thought this value was the "sigDigits" value set in pool as well as the one you need to devide on.
